# Generated by Django 5.2.6 on 2025-11-28 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("circuits", "0001_initial"),
        ("pilots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField(unique=True, verbose_name="Année")),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Saison active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Saison",
                "verbose_name_plural": "Saisons",
                "ordering": ["-annee"],
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de la course"),
                ),
                ("date", models.DateField(verbose_name="Date de la course")),
                (
                    "heure",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Heure de départ"
                    ),
                ),
                (
                    "meteo",
                    models.CharField(
                        choices=[
                            ("ensoleille", "Ensoleillé"),
                            ("nuageux", "Nuageux"),
                            ("pluvieux", "Pluvieux"),
                            ("orage", "Orage"),
                        ],
                        default="ensoleille",
                        max_length=20,
                        verbose_name="Météo",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "numero_manche",
                    models.PositiveIntegerField(
                        help_text="Position dans le calendrier",
                        verbose_name="Numéro de manche",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "circuit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="circuits.circuit",
                        verbose_name="Circuit",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="races",
                        to="races.season",
                        verbose_name="Saison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["season", "date"],
                "unique_together": {("season", "numero_manche")},
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(verbose_name="Position finale"),
                ),
                (
                    "points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Points marqués"
                    ),
                ),
                (
                    "temps_total",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Temps total"
                    ),
                ),
                (
                    "meilleur_tour",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Meilleur tour",
                    ),
                ),
                (
                    "tours_completés",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Tours complétés"
                    ),
                ),
                (
                    "statut_course",
                    models.CharField(
                        default="Terminé",
                        help_text="Terminé, Abandon, DNF, etc.",
                        max_length=50,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_results",
                        to="pilots.pilote",
                        verbose_name="Pilote",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="races.race",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Résultat de course",
                "verbose_name_plural": "Résultats de course",
                "ordering": ["race", "position"],
                "unique_together": {("race", "pilot")},
            },
        ),
        migrations.CreateModel(
            name="Championship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total de points"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(verbose_name="Position au classement"),
                ),
                (
                    "victoires",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de victoires"
                    ),
                ),
                (
                    "podiums",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Nombre de podiums"
                    ),
                ),
                (
                    "courses_completes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Courses terminées"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="championships",
                        to="pilots.pilote",
                        verbose_name="Pilote",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="championships",
                        to="races.season",
                        verbose_name="Saison",
                    ),
                ),
            ],
            options={
                "verbose_name": "Classement championnat",
                "verbose_name_plural": "Classements championnat",
                "ordering": ["season", "position"],
                "unique_together": {("season", "pilot")},
            },
        ),
    ]
