# Generated by Django 5.2.6 on 2025-11-29 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pilots", "0001_initial"),
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RaceStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pneu_depart",
                    models.CharField(
                        choices=[
                            ("soft", "Soft (Tendre)"),
                            ("medium", "Medium (Moyen)"),
                            ("hard", "Hard (Dur)"),
                            ("intermediate", "Intermédiaire"),
                            ("wet", "Pluie"),
                        ],
                        max_length=20,
                        verbose_name="Pneu de départ",
                    ),
                ),
                (
                    "pneu_stint2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soft", "Soft (Tendre)"),
                            ("medium", "Medium (Moyen)"),
                            ("hard", "Hard (Dur)"),
                            ("intermediate", "Intermédiaire"),
                            ("wet", "Pluie"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Pneu stint 2",
                    ),
                ),
                (
                    "pneu_stint3",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soft", "Soft (Tendre)"),
                            ("medium", "Medium (Moyen)"),
                            ("hard", "Hard (Dur)"),
                            ("intermediate", "Intermédiaire"),
                            ("wet", "Pluie"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Pneu stint 3",
                    ),
                ),
                (
                    "pneu_stint4",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("soft", "Soft (Tendre)"),
                            ("medium", "Medium (Moyen)"),
                            ("hard", "Hard (Dur)"),
                            ("intermediate", "Intermédiaire"),
                            ("wet", "Pluie"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Pneu stint 4",
                    ),
                ),
                (
                    "nombre_pitstops",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Nombre de pitstops"
                    ),
                ),
                (
                    "tour_pitstop1",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tour pitstop 1"
                    ),
                ),
                (
                    "tour_pitstop2",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tour pitstop 2"
                    ),
                ),
                (
                    "tour_pitstop3",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tour pitstop 3"
                    ),
                ),
                (
                    "consommation_carburant",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Carburant prévu en kg",
                        max_digits=5,
                        verbose_name="Consommation carburant (kg)",
                    ),
                ),
                (
                    "meteo_prevue",
                    models.CharField(
                        choices=[
                            ("ensoleille", "Ensoleillé"),
                            ("nuageux", "Nuageux"),
                            ("pluvieux", "Pluvieux"),
                            ("orage", "Orage"),
                        ],
                        max_length=20,
                        verbose_name="Météo prévue",
                    ),
                ),
                (
                    "temperature_piste",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Température piste (°C)",
                    ),
                ),
                (
                    "resultat_strategie",
                    models.CharField(
                        choices=[
                            ("reussi", "Réussi"),
                            ("partiellement_reussi", "Partiellement réussi"),
                            ("echec", "Échec"),
                            ("non_applique", "Non appliqué"),
                        ],
                        default="non_applique",
                        max_length=30,
                        verbose_name="Résultat de la stratégie",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notes sur la stratégie"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="pilots.pilote",
                        verbose_name="Pilote",
                    ),
                ),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to="races.race",
                        verbose_name="Course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stratégie de course",
                "verbose_name_plural": "Stratégies de course",
                "ordering": ["race", "pilot"],
                "unique_together": {("race", "pilot")},
            },
        ),
    ]
