# Generated by Django 5.2.6 on 2025-11-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('equipe', models.CharField(max_length=150)),
                ('nationalite', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField(default=0)),
                ('victoires', models.IntegerField(default=0)),
                ('podiums', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pilote',
                'verbose_name_plural': 'Pilotes',
                'ordering': ['-victoires'],
            },
        ),
    ]
