# Generated by Django 5.2.6 on 2025-11-29 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pilots", "0001_initial"),
        ("races", "0002_racestrategy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nom de l'équipe"
                    ),
                ),
                (
                    "nom_complet",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Nom complet",
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Budget en millions USD",
                        max_digits=12,
                        verbose_name="Budget annuel",
                    ),
                ),
                (
                    "quartier_general",
                    models.CharField(max_length=200, verbose_name="Quartier général"),
                ),
                ("pays", models.CharField(max_length=100, verbose_name="Pays")),
                (
                    "directeur",
                    models.CharField(max_length=200, verbose_name="Directeur d'équipe"),
                ),
                (
                    "directeur_technique",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Directeur technique",
                    ),
                ),
                (
                    "moteur",
                    models.CharField(max_length=100, verbose_name="Moteur utilisé"),
                ),
                (
                    "chassis",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Châssis"
                    ),
                ),
                (
                    "sponsor_principal",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Sponsor principal",
                    ),
                ),
                (
                    "autres_sponsors",
                    models.TextField(
                        blank=True, null=True, verbose_name="Autres sponsors"
                    ),
                ),
                (
                    "annee_creation",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Année de création"
                    ),
                ),
                (
                    "championnats_constructeurs",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de championnats constructeurs gagnés",
                        verbose_name="Championnats constructeurs",
                    ),
                ),
                (
                    "championnats_pilotes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Nombre de championnats pilotes gagnés",
                        verbose_name="Championnats pilotes",
                    ),
                ),
                (
                    "couleur_principale",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Couleur principale",
                    ),
                ),
                (
                    "couleur_secondaire",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Couleur secondaire",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, null=True, verbose_name="URL du logo"),
                ),
                (
                    "actif",
                    models.BooleanField(default=True, verbose_name="Équipe active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Équipe",
                "verbose_name_plural": "Équipes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="TeamPilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_pilote",
                    models.PositiveIntegerField(verbose_name="Numéro du pilote"),
                ),
                (
                    "pilote_principal",
                    models.BooleanField(default=False, verbose_name="Pilote principal"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_contracts",
                        to="pilots.pilote",
                        verbose_name="Pilote",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_pilots",
                        to="races.season",
                        verbose_name="Saison",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_pilots",
                        to="teams.team",
                        verbose_name="Équipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pilote d'équipe",
                "verbose_name_plural": "Pilotes d'équipe",
                "ordering": ["season", "team", "-pilote_principal"],
                "unique_together": {("team", "pilot", "season")},
            },
        ),
    ]
