# Generated by Django 5.2.6 on 2025-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom du circuit"),
                ),
                ("pays", models.CharField(max_length=100, verbose_name="Pays")),
                (
                    "ville",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "longueur",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Longueur du circuit en kilomètres",
                        max_digits=5,
                        verbose_name="Longueur (km)",
                    ),
                ),
                (
                    "type_circuit",
                    models.CharField(
                        choices=[
                            ("urbain", "Urbain"),
                            ("permanent", "Permanent"),
                            ("semi-permanent", "Semi-permanent"),
                        ],
                        default="permanent",
                        max_length=20,
                        verbose_name="Type de circuit",
                    ),
                ),
                (
                    "nombre_tours",
                    models.PositiveIntegerField(
                        help_text="Nombre de tours en course",
                        verbose_name="Nombre de tours",
                    ),
                ),
                (
                    "premiere_course",
                    models.IntegerField(
                        blank=True,
                        help_text="Année de la première course F1",
                        null=True,
                        verbose_name="Première course F1",
                    ),
                ),
                (
                    "record_tour",
                    models.CharField(
                        blank=True,
                        help_text="Temps du record (ex: 1:24.123)",
                        max_length=20,
                        null=True,
                        verbose_name="Record du tour",
                    ),
                ),
                (
                    "detenteur_record",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Détenteur du record",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de l'image du circuit",
                        null=True,
                        verbose_name="URL de l'image",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Indique si le circuit est utilisé cette saison",
                        verbose_name="Circuit actif",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circuit",
                "verbose_name_plural": "Circuits",
                "ordering": ["nom"],
            },
        ),
    ]
